name: codacy analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.18, 1.19 ]

    steps:
      - uses: actions/checkout@v3

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.2.0
