name: linters

on: [ push, pull_request ]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.18, 1.19 ]

    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -v
